name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.2.0
  flutter_contacts:
    path: ../
  image_picker: ^1.1.1
  pretty_json: ^2.0.0
  prompt_dialog: ^1.0.16

flutter:
  uses-material-design: true
